# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# ID3 tag music genres are surprisingly specific.

genres = Hash[[
  "Blues",
  "Classic Rock",
  "Country",
  "Dance",
  "Disco",
  "Funk",
  "Grunge",
  "Hip-Hop",
  "Jazz",
  "Metal",
  "New Age",
  "Oldies",
  "Other",
  "Pop",
  "R&B",
  "Rap",
  "Reggae",
  "Rock",
  "Techno",
  "Industrial",
  "Alternative",
  "Ska",
  "Death Metal",
  "Pranks",
  "Soundtrack",
  "Euro-Techno",
  "Ambient",
  "Trip-Hop",
  "Vocal",
  "Jazz+Funk",
  "Fusion",
  "Trance",
  "Classical",
  "Instrumental",
  "Acid",
  "House",
  "Game",
  "Sound Clip",
  "Gospel",
  "Noise",
  "Alternative Rock",
  "Bass",
  "Soul",
  "Punk",
  "Space",
  "Meditative",
  "Instrumental Pop",
  "Instrumental Rock",
  "Ethnic",
  "Gothic",
  "Darkwave",
  "Techno-Industrial",
  "Electronic",
  "Pop-Folk",
  "Eurodance",
  "Dream",
  "Southern Rock",
  "Comedy",
  "Cult",
  "Gangsta",
  "Top 40",
  "Christian Rap",
  "Pop/Funk",
  "Jungle",
  "Native US",
  "Cabaret",
  "New Wave",
  "Psychadelic",
  "Rave",
  "Showtunes",
  "Trailer",
  "Lo-Fi",
  "Tribal",
  "Acid Punk",
  "Acid Jazz",
  "Polka",
  "Retro",
  "Musical",
  "Rock & Roll",
  "Hard Rock",
  "Folk",
  "Folk-Rock",
  "National Folk",
  "Swing",
  "Fast Fusion",
  "Bebob",
  "Latin",
  "Revival",
  "Celtic",
  "Bluegrass",
  "Avantgarde",
  "Gothic Rock",
  "Progressive Rock",
  "Psychedelic Rock",
  "Symphonic Rock",
  "Slow Rock",
  "Big Band",
  "Chorus",
  "Easy Listening",
  "Acoustic",
  "Humour",
  "Speech",
  "Chanson",
  "Opera",
  "Chamber Music",
  "Sonata",
  "Symphony",
  "Booty Bass",
  "Primus",
  "Porn Groove",
  "Satire",
  "Slow Jam",
  "Club",
  "Tango",
  "Samba",
  "Folklore",
  "Ballad",
  "Power Ballad",
  "Rhythmic Soul",
  "Freestyle",
  "Duet",
  "Punk Rock",
  "Drum Solo",
  "Acapella",
  "Euro-House",
  "Dance Hall",
  "Goa",
  "Drum & Bass",
  "Club - House",
  "Hardcore",
  "Terror",
  "Indie",
  "BritPop",
  "Negerpunk",
  "Polsk Punk",
  "Beat",
  "Christian Gangsta Rap",
  "Heavy Metal",
  "Black Metal",
  "Crossover",
  "Contemporary Christian",
  "Christian Rock",
  "Merengue",
  "Salsa",
  "Thrash Metal",
  "Anime",
  "JPop",
  "Synthpop"
].map { |genre| [genre, Genre.find_or_create_by(name: genre)] }]

artists = [
  {name: "alt-J"},
  {name: "Snoop Dogg"},
  {name: "Rick Ross"},
  {name: "Kirby"},
  {name: "blAck pArty"},
  {name: "Joey Purp"},
  {name: "Smino"},
  {name: "Angelo Mota"},
  {name: "MF Doom"},
  {name: "Syd"},
  {name: "Hare Squead"},
  {name: "Jay Electronica"},
  {name: "Talib Kweli"},
  {name: "Mick Jenkins"},
  {name: "John Legend"},
  {name: "Nipsy Hustle"},
  {name: "DJ Khaled"},
  {name: "Demi Lovato"},
  {name: "BJ the Chicago Kid"},
  {name: "Leon Bridges"},
  {name: "Ben Platt"},
  {name: "Maggie Rogers"},
  {name: "Raury"},
  {name: "D.I.D."},
  {name: "Joji"},
  {name: "Jamie xx"},
  {name: "Dispatch"},
  {name: "Vic Menca"},
  {name: "Chance"},
  {name: "Joey Badass"},
  {name: "The Coup"},
  {name: "fun"},
  {name: "Kyle"},
  {name: "Tobi Lou"},
  {name: "Young Thug"},
  {name: "Shakira"},
  {name: "Adele"},
  {name: "Kanye"},
  {name: "Beyonce"},
  {name: "Jay-Z"},
]

artists.each{|artist| Artist.find_or_create_by(name: artist)}

# songs = [
#   {title: "alt-J"},
#   {title: "Snoop Dogg"},
#   {title: "Rick Ross"},
#   {title: "Kirby"},
#   {title: "blAck pArty"},
#   {title: "Joey Purp"},
#   {title: "Smino"},
#   {title: "Angelo Mota"},
#   {title: "MF Doom"},
#   {title: "Syd"},
#   {title: "Hare Squead"},
#   {title: "Jay Electronica"},
#   {title: "Talib Kweli"},
#   {title: "Mick Jenkins"},
#   {title: "John Legend"},
#   {title: "Nipsy Hustle"},
#   {title: "DJ Khaled"},
#   {title: "Demi Lovato"},
#   {title: "BJ the Chicago Kid"},
#   {title: "Leon Bridges"},
#   {title: "Ben Platt"},
#   {title: "Maggie Rogers"},
#   {title: "Raury"},
#   {title: "D.I.D."},
#   {title: "Joji"},
#   {title: "Jamie xx"},
#   {title: "Dispatch"},
#   {title: "Vic Menca"},
#   {title: "Chance"},
#   {title: "Joey Badass"},
#   {title: "The Coup"},
#   {title: "fun"},
#   {title: "Kyle"},
#   {title: "Tobi Lou"},
#   {title: "Young Thug"},
#   {title: "Shakira"},
#   {title: "Adele"},
#   {title: "Kanye"},
#   {title: "Beyonce"},
#   {title: "Jay-Z"},
# ]

# songs.each{|song| Song.find_or_create_by(title: song, artist: Artist.all.sample, genre )}